apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        app.kubernetes.io/name: backend
        app.kubernetes.io/part-of: easytravel
    spec:
      containers:
        - env:
            - name: ET_DATABASE_LOCATION
              value: mongodb-service:27017
            - name: ET_MONGO_AUTH_DB
              value: admin
            - name: ET_DATABASE_USER
              value: etAdmin
            - name: ET_DATABASE_PASSWORD
              value: adminadmin
          image: dynatrace/easytravel-backend
          imagePullPolicy: Always
          name: backend
          ports:
            - containerPort: 8009
              protocol: TCP
            - containerPort: 8005
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "500Mi"
            limits:
              memory: "500Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  ports:
    - name: port5
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: port3
      port: 8009
      protocol: TCP
      targetPort: 8009
    - name: port4
      port: 8005
      protocol: TCP
      targetPort: 8005
  selector:
    app: backend
  type: ClusterIP
