apiVersion: v1
kind: Pod
metadata:
  name: mongodb-contentcreator
spec:
  restartPolicy: OnFailure
  containers:
    - image: dynatrace/easytravel-mongodb-content-creator
      name: mongodb-contentcreator
      imagePullPolicy: Always
      env:
        - name: ET_DATABASE_LOCATION
          value: mongodb-service:27017
        - name: ET_MONGO_AUTH_DB
          value: admin
        - name: ET_DATABASE_USER
          value: etAdmin
        - name: ET_DATABASE_PASSWORD
          value: adminadmin
      resources:
        requests:
          memory: "200Mi"
        limits:
          memory: "200Mi"
